version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es01
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - elastic
  kib:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kib01
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    driver: bridge