[common]
worker_count = 20

[tfinv]
credentials_file_path = "config/gapi-keys.json"
spreadsheet_id = "1MmiHyYiXeAnstoNU2mN3EKUUE0JpWCc8V62WF8MYkiE"
mapping_worksheet_name = "tf_mappings"

[mirador]
# endpoint = "http://localhost:9200/"
# user_name = ""
# password = ""
endpoint = "https://elasticsearch.sg.aws.grabsecurity.com:443"
user_name = ""
password = ""
telescope_index_tmpl = "telescope"
vuln_management_index_tmpl = "vuln_management_test"

[brahma]
#local or aws
location = "local"
inventory_local_path = "data/brahma.prd.json"
inventory_aws_s3_bucket = "g-devsecops-home"
inventory_aws_s3_key = "resources/grab-mobility-aws-accounts.json"
platform_filter = "aws"